server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/ems_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS} # 1  hour
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS} # 1  hour
  secret: ${JWT_SECRET}